In [1]:
import math
import numpy as np
from scipy.misc import derivative

利用scipy中的derivative 函数进行求导
2.6 x+sinx-1 = 0
利用Aitken加速法求解方程在x0 = 1/2附近的唯一根
（利用含l的Aitken加速法

l为函数在该点附近的导数，要求函数在该点的导数变化值较小

即要求函数的二阶导的绝对值较小

故而，我们首先要验证二阶导的绝对值较小

然后求出该点的导数

利用公式：
$$
x_{k+1} = (1-l)^{-1}[f(x_k) - l \ast x_k]
$$

由于题目中 __a__ 与 __l__ 符号相反，故而`a=-l`

In [2]:
def func1(x):
    return 1-math.sin(x)

In [3]:
# 手算可得，二阶导为sinx 一阶导为-cosx
print(math.sin(1/2))
print(-math.cos(1/2))

0.479425538604203
-0.8775825618903728


In [4]:
l = derivative(func1,0.5,1e-6,1)
print(l)
# 可得结果在误差范围内

-0.8775825618423383


In [5]:
def Aitken_l(x0, func,tol):
    l = derivative(func, x0, 1e-8, 1)
    print("l = ",l)
    x1 = (func(x0) - l*x0)/(1-l)
    print("第一步迭代=",x1)
    k = 0
    # 先进行两步迭代缩小范围
    while abs(x1- x0) > tol:
        x2 = (func(x1) - l*x1)/(1-l)
        # 存储结果方便计算前后误差
        x0 = x1
        x1 = x2
        k+=1
        # 每四次更新一次导数值
        if k % 4 == 0:
            l = derivative(func, x2, 1e-8, 1)
    print("总迭代次数：",k)
    return x2

In [6]:
# 手算值
((0.8776*0.5)-math.sin(0.5)+1)/(1+0.8776)

0.5109578511907739

In [7]:
# 
Aitken_l(1/2, func1, 1/2 * 1e-3)

l =  -0.8775825621754052
第一步迭代= 0.5109579529605127
总迭代次数： 1


0.5109733856205185

In [8]:
0.5110-0.5109

9.999999999998899e-05

利用书上例题验证Aitken加速迭代法的正确性

In [9]:
Aitken_l(1, lambda x: (x+1)**(1/3), 1e-8)

l =  0.2099868390281756
第一步迭代= 1.3290085061053094
总迭代次数： 5


1.3247179572447458

In [10]:
# 书上为 1.324717957244746
1.324717957244746 - 1.3247179572447985

-5.240252676230739e-14

# 2.7

$\vec{a}$  向量

$\overline{a}$ 平均值

$\widehat{a}$ (线性回归，直线方程) y尖

$\widetilde{a}$ 颚化符号  等价无穷小

$\dot{a}$   一阶导数

$\ddot{a}$  二阶导数

不带`l`的Aitken加速迭代法可由带l的Aitken加速迭代法得到

其关键是近似求解`l`,即$\phi{(xk)}$, 每次利用新计算出来的近似的$\phi{(xk)}$去替换`l`

$$
\widetilde{x}_{k+1} = \phi{(x_k)}, \widehat{x}_{k+1} = \phi{(\widetilde{x}_{k+1})}
$$
这里的代换是利用$x_k$去求得近似的\phi{(\widetilde{x}_{k+1})}，为的是得到两个有关$\phi()$这个函数的两个等式

从而通过等式，利用Tayler展开去近似求解`l`

则， 由上述式子，利用泰勒展开可得

$$
x^* - \widetilde{x}_{k+1} \approx l(x^* - x_k), x^* - \widehat{x}_{k+1} \approx l(x^* - \widetilde{x}_{k+1})
$$
从而有：
$$
 l = \frac{x^* - \widetilde{x}_{k+1}}{(x^* - x_k)}
 \qquad
 x^* = \widehat{x}_{k+1} + \frac{x^* - \widetilde{x}_{k+1}^2}{x^* - x_k}
$$
解得：
$$
    x^* \approx \widehat{x}_{k+1} - \frac{(\widehat{x}_{k+1} - \widetilde{x}_{k+1})^2}{\widehat{x}_{k+1} - 2*\widetilde{x}_{k+1} + x_k}
$$
由于$x^* \approx x_{k+1}$
则：
$$
 x_{k+1} = \widehat{x}_{k+1} - \frac{(\widehat{x}_{k+1} - \widetilde{x}_{k+1})^2}{\widehat{x}_{k+1} - 2*\widetilde{x}_{k+1} + x_k}
$$
将其中的$\widehat{x}_{k+1}$与$\widetilde{x}_{k+1}$ 替换为 $\phi{(\phi{(x_k))}}$ 与$\phi{(x_k)}$
$$
 x_{k+1} = \phi{(\phi{(x_k))}} - \frac{(\phi{(\phi{(x_k))}} - \phi{(x_k)})^2}{\phi{(\phi{(x_k))}} - 2*\phi{(x_k)} + x_k}
$$

在2.7中，将“$\phi(x)$替换为$x - f(x)$代入上述公式，可得：
$$
x_{k+1} = x_k - \frac{f(x_k)^2}{f(x_k)-f(x_k - f(x_k))}
$$
即Steffsen加速迭代法的公式
可以看见，对于求解0点问题，Steffsen方法本质上是Aitken加速迭代法的一种特殊情况

这里也可以看出，Aitken加速迭代法其实和Steffsen方法做了同样的工作，即利用两点的弦来近似曲线的曲度，从而形成快速收敛的格式，两者在求解方程时所用到的思想其实是相近的！

# 2.8

_非线性方程组的Picard迭代法_

证明非线性方程组全局收敛：

1. $\Phi(x)$收敛于$D_0$
2. |$\Phi^{'}(x)$| < 0

In [11]:
def d_Picard():
    x0 = 0
    y0 = 0
    k = 20
    while k>0:
        x1 = 0.5*(math.cos(x0)-math.sin(y0))
        y1 = 0.5*(math.sin(x0)+math.cos(y0))
        print(x1,y1)
        x0,y0 = x1,y1
        k-=1

In [12]:
d_Picard()

0.5 0.5
0.19907851164308488 0.6785040502472879
0.17631006101217495 0.4881393088753382
0.2577571380790325 0.5293025298940379
0.2310163535007379 0.5590359414153968
0.22153251938261248 0.5383669033457366
0.2314136384170124 0.5391360594927063
0.22997417692728994 0.5437531258150355
0.22816041505742857 0.5418627042085488
0.22917568747512318 0.5414677537104109
0.22922982320720547 0.5420639867557483
0.22896824728752807 0.5419366230181328
0.22905250414842748 0.5418421026978179
0.22908342988060904 0.5419075059114628
0.22905190184703983 0.541905699234766
0.22905625529092577 0.5418908129125337
0.22906213784042395 0.5418967716907077
0.2290589174481069 0.541898099492772
0.22905871427858654 0.5418961889394412
0.2290595557603738 0.5418965827036752


In [13]:
math.cos(0.54189629760355)

0.8567321849632784

Picard 迭代法对应的函数：function2_8

In [14]:
def function2_8(x):
    return np.array([[(math.cos(x[0])-math.sin(x[1]))*0.5], [(math.sin(x[0])+math.cos(x[1]))*0.5]])

In [15]:
function2_8(np.array([[0.19907851],[0.67850405]]))

array([[0.17631006],
       [0.48813931]])

Newton法迭代公式

In [16]:
def func_nt_2_8(v):
    v = v.flatten()
    print("v shape is:",v.shape)
    x, y = v[0], v[1]
    return np.array([  [(math.cos(x)-math.sin(y))*0.5- x] , [(math.sin(x)+math.cos(y))*0.5 - y]  ])

In [17]:
# func_nt_2_8([0,0])
print(np.array([[0],[0]]))
print(func_nt_2_8(np.array([[0],[0]])))

[[0]
 [0]]
v shape is: (2,)
[[0.5]
 [0.5]]


### 手动运算过程

### 求Jacobi矩阵的函数实现

In [19]:
def cal_Jacobi(x, func, eps):
    # n 表示向量的长度
    n = x.shape[0]
    jacobi = np.zeros((n,n))
    
    jacobi[0][1] = 0
    for i in range(n):
        for j in range(n):
            # 需要指定数据类型
            temp1,temp2 = np.array(x,dtype=float),np.array(x,dtype=float)
            # 需要进行求导的元素加上一个极小量
            temp1[j][0] += eps
            temp2[j][0] -= eps
            t = (func(temp1)[i][0]-func(temp2)[i][0])/(2*eps)
            # i， j位置上的元素是所得向量的[i]号方程结果与eps的除
            jacobi[i][j] = t
    return jacobi

测试代码

In [20]:
# 测试一下：
cal_Jacobi(np.array([[0],[0]]),function2_8,1e-8)

array([[ 0. , -0.5],
       [ 0.5,  0. ]])

In [21]:
cal_Jacobi(np.array([[0.5],[0.5]]),function2_8,1e-8)

array([[-0.23971277, -0.43879128],
       [ 0.43879128, -0.23971277]])

In [22]:
print(-math.sin(0.5)*0.5)
print(-0.5*math.cos(0.5))

-0.2397127693021015
-0.4387912809451864


完美符合了手动求出来的Jacobi矩阵!

In [23]:
temp = cal_Jacobi(np.array([[0.5],[0.5]]),function2_8,1e-8)
print(temp)
temp = np.matrix(temp)
print(temp.I)
print(temp.I.dot(np.array([[0.17631006101217495],[0.4881393088753382]])))
print(temp.I.dot(function2_8(np.array([[0.5],[0.5]]))))
print(function2_8(np.array([[0.5],[0.5]])))
print(np.array([[0.5],[0.5]]) - np.matrix(temp).I.dot([[0.19907851],[0.67850405]]))

[[-0.23971277 -0.43879128]
 [ 0.43879128 -0.23971277]]
[[-0.95885108  1.75516511]
 [-1.75516511 -0.95885108]]
[[ 0.68770999]
 [-0.77750617]]
[[ 0.99999999]
 [-1.        ]]
[[0.19907851]
 [0.67850405]]
[[-0.49999999]
 [ 1.5       ]]


In [24]:
cal_Jacobi(np.array([[0],[0]]),func_nt_2_8,1e-8)

v shape is: (2,)
v shape is: (2,)
v shape is: (2,)
v shape is: (2,)
v shape is: (2,)
v shape is: (2,)
v shape is: (2,)
v shape is: (2,)


array([[-1. , -0.5],
       [ 0.5, -1. ]])

In [26]:
# 牛顿迭代法的迭代格式
def func_nt_2_8(v):
    x = float(v[0][0])
    y = float(v[1][0])
    return np.array([[(math.cos(x)-math.sin(y))*0.5- x] , [(math.sin(x)+math.cos(y))*0.5 - y]])

In [27]:
tset = np.array([[0],[0]])
test = tset
print(test[0][0])

0


In [28]:
func_nt_2_8(np.array([[0],[0]]))
print(func_nt_2_8(np.array([[0.22866336],[0.54232995]])))

[[ 0.00025526]
 [-0.00073779]]


In [29]:
print(func_nt_2_8(np.array([[0.22866336],[0.54232995]])))

[[ 0.00025526]
 [-0.00073779]]


In [30]:
def Newton_2_8(x0,tol):
    x0 = np.array([[0.2],[0.6]])
    k = 10
    # k: iteration times
    while k > 0:
        #  计算Jacobi矩阵的逆矩阵
        temp = np.matrix(cal_Jacobi(x0,func_nt_2_8,1e-8)).I
        # 计算迭代矩阵
        x1 = x0 -  temp.dot(func_nt_2_8(x0))
        x0 = x1
        k -= 1
        # lm *= 0.5
        print("Thisis x1:",x1)
    return x1

In [31]:
Newton_2_8(0,0)

[[0.2]
 [0.6]]
x0is: [[0.2]
 [0.6]]
Matrix shapew is: (2, 2)
function result = [[ 0.00771205]
 [-0.08799753]]
Thisis x1: [[0.22866336]
 [0.54232995]]
x0is: [[0.22866336]
 [0.54232995]]
Matrix shapew is: (2, 2)
function result = [[ 0.00025526]
 [-0.00073779]]
Thisis x1: [[0.22905927]
 [0.54189675]]
x0is: [[0.22905927]
 [0.54189675]]
Matrix shapew is: (2, 2)
function result = [[-1.3955740e-08]
 [-4.9076135e-08]]
Thisis x1: [[0.22905927]
 [0.54189672]]
x0is: [[0.22905927]
 [0.54189672]]
Matrix shapew is: (2, 2)
function result = [[ 5.55111512e-17]
 [-6.66133815e-16]]
Thisis x1: [[0.22905927]
 [0.54189672]]
x0is: [[0.22905927]
 [0.54189672]]
Matrix shapew is: (2, 2)
function result = [[-5.55111512e-17]
 [ 0.00000000e+00]]
Thisis x1: [[0.22905927]
 [0.54189672]]
x0is: [[0.22905927]
 [0.54189672]]
Matrix shapew is: (2, 2)
function result = [[0.]
 [0.]]
Thisis x1: [[0.22905927]
 [0.54189672]]
x0is: [[0.22905927]
 [0.54189672]]
Matrix shapew is: (2, 2)
function result = [[0.]
 [0.]]
Thisis x1:

matrix([[0.22905927],
        [0.54189672]])

最终结果与

In [124]:
function2_8([0,0])

array([[0.5],
       [0.5]])