In [2]:
import numpy as np

In [3]:
import math

求矩阵二阶范数

In [7]:
A = np.array([[-2, 1, 0],[1,-2,1],[0,1,-2]])
t = A.dot(A.T)
print(t)
print(A.T)
print(A.T.dot(A))
a, b = np.linalg.eig(t)
print(math.sqrt(max(a)))

[[ 5 -4  1]
 [-4  6 -4]
 [ 1 -4  5]]
[[-2  1  0]
 [ 1 -2  1]
 [ 0  1 -2]]
[[ 5 -4  1]
 [-4  6 -4]
 [ 1 -4  5]]
3.414213562373096


## 2.1

In [2]:
def function1(x:int)->int:
    return x - 2**(-x)

In [3]:
# 假定左侧一定为负数
def bi(left:int, right:int, e:int)->int:
    k = 0
    while right - left > e:
        # 中间值大于0， 则根应当在左侧，需要更新右侧区间
        k+= 1
        mid = (left + right)/2
        res = function1(mid)
        if res > 0:
            right = mid
        elif res < 0:
            left = mid
    print(k)
    print(mid)

In [4]:
bi(0, 1, 0.0005)

11
0.64111328125


In [5]:
function1(1443/2048)

0.09097292945947055

## 2.2

In [10]:
def function2(x):
    return 2*math.cos(x) - 1 - math.sin(x)
x2 = 0.67
x1 = math.pi/4
x3 = x2 - (x2-x1)*function2(x2)/(function2(x2)-function2(x1))
print(x3)

0.644303360599398


In [11]:
# 测试Function2是否正确
function2(0)

1.0

In [12]:
# 用作Steffensen方法的辅助函数，也可以不使用，这里是为了让代码看起来更加简洁
def function3(x0):
    return function2(x0 - function2(x0))

In [13]:
# Function3（0）应当和Function2（0）是同一个数字
function3(0)

0.922075596544176

In [15]:
function2(-1)

0.922075596544176

In [17]:
x0 = 0
x1 = x0 - function2(x0)*function2(x0)/(function2(x0)-function3(x0))
print(x1)
x0 = x1
x1 = x0 - function2(x0)*function2(x0)/(function2(x0)-function3(x0))
print(x1)

-12.832950342275112
-14.289792077227885


## 2.3

In [29]:
def Steffsen(x0):
    k = 10
    while k > 0:
        x1 = x0 - function2(x0)*function2(x0)/(function2(x0)-function3(x0))
        x0 = x1
        print(x1)
        k -= 1
    print(function2(x1))

In [30]:
Steffsen(0)

-12.832950342275112
-14.289792077227885
-14.130872141547208
-14.137157066125226
-14.13716694112969
-14.137166941154069
-14.137166941154069
-14.137166941154069
-14.137166941154069
-14.137166941154069
1.1102230246251565e-15


In [26]:
Steffsen(math.pi/4)

0.6518968616471251
0.6435524348604265
0.6435011107687033
0.6435011087932843
0.6435011087932844
0.6435011087932845
0.6435011087932844
0.6435011087932845
0.6435011087932844
0.6435011087932845
-2.220446049250313e-16


In [16]:
function2(0)/ (function2(0)-function3(0))

12.832950342275112

In [31]:
5 ** (1/3)

1.7099759466766968

In [32]:
def fff(x):
    return 2 * x /3*((1+x*x)**(1/3)) - 1

In [38]:
fff(1.5)

0.4812480342036851

In [36]:
fff(2 ** (1/3))

0.15311686226040067

## 2.4

In [39]:
def func4(x0):
    return (1+x0*x0) ** (1/3)

In [50]:
def func5(x0):
    return 1+1/(x0*x0)

In [57]:
def func6(x0):
    return 1/(x0 - 1) ** (0.5)

In [51]:
func5(2)

1.25

### Picard 迭代法

In [59]:
def Picard(x0, k, func):
    while k>0:
        x1 = func(x0)
        x0 = x1
        print(x1)
        k-=1
    return x0

In [61]:
Picard(1.5, 10, lambda x0: (1+x0*x0) ** (1/3))

1.4812480342036851
1.4727057296393942
1.4688173136644993
1.4670479732005974
1.466243010114747
1.4658768201688133
1.465710240775865
1.4656344652385098
1.4655999958533155
1.4655843161956508


1.4655843161956508